### ISSUE TITLE
q1.cpp not working for all cases.

### ISSUE THREAD

**Issue by iCHAIT** [nickedes/Oopsy#1]
When the input string entered comprises of multiple words separated by spaces then the vowel count shown is not correct.

**Comment by iCHAIT** [comment]
Also currently it not handles case sensitivity!

**Comment by nickedes** [comment]
Pull requests will be accepted :tongue:

**Comment by nickedes** [comment]
I dont know how to work with inputs separated by spaces. :(

**Comment by kwikadi** [comment]
I think using String data type should fix that.

**Comment by iCHAIT** [comment]
Or maybe using **getline** when taking the input.
